#!/usr/bin/env bash
#
# Tests for `wf hygiene check` — the repo-hygiene linter (file length, Go function
# length, comment discipline) with ratchet semantics against a git base.
# Run: bash tools/cli/tests/hygiene_test.sh   (exit 0 = all pass)
# wf2-source-only — never rendered into an install target.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI="$(cd "$HERE/.." && pwd)"
ROOT="$(cd "$CLI/../.." && pwd)"
WF="$CLI/wf"
PYTHON="$(command -v python3)"
[ -x "$ROOT/tools/.venv/bin/python" ] && PYTHON="$ROOT/tools/.venv/bin/python"

pass=0; fail=0
ok()  { pass=$((pass+1)); echo "  ok   - $1"; }
bad() { fail=$((fail+1)); echo "  FAIL - $1"; echo "         $2"; }
jget() { "$PYTHON" -c 'import sys,json; d=json.loads(sys.argv[1]); print(eval(sys.argv[2]))' "$1" "$2"; }

PROJ="$(mktemp -d)"; mkdir -p "$PROJ/.wf"
cat > "$PROJ/.wf/config.yaml" <<'YAML'
version: 1
paths: {}
hygiene:
  file_warn: 20
  file_error: 40
  func_error: 10
  comment_block_max: 4
  comment_ratio_warn: 0.4
  agents_md_max: 10
YAML
git -C "$PROJ" init -q; git -C "$PROJ" config user.email t@t; git -C "$PROJ" config user.name t

# Run from inside the project: hygiene lints the tree the caller stands in.
wf() { (cd "$PROJ" && "$PYTHON" "$WF" "$@" --config "$PROJ/.wf/config.yaml"); }

# helper: emit N lines of trivial go statements
golines() { for i in $(seq 1 "$1"); do echo "var x$i = $i"; done; }

# ---------------------------------------------------------------------------
# full-sweep mode (no --diff-base): reports everything, always exits 0
# ---------------------------------------------------------------------------

{ echo "package p"; golines 45; } > "$PROJ/long.go"                  # > file_error(40) → H1 error
{ echo "package p"; golines 25; } > "$PROJ/midsize.go"               # > file_warn(20) → H1 warn
cat > "$PROJ/bigfunc.go" <<'GO'
package p

func Big() {
	a := 1
	a = 2
	a = 3
	a = 4
	a = 5
	a = 6
	a = 7
	a = 8
	a = 9
	a = 10
	_ = a
}
GO
cat > "$PROJ/comments.go" <<'GO'
package p

// one
// two
// three
// four
// five
// six
var a = 1

// The evaluator honours REQ-42 by resolving the effective set
// before ADR-016's single plane applies, which means the
// verdict writer never sees the legacy path here.
var b = 2

// [REQ:REQ-42] The system shall resolve the effective requirement set per project.
var c = 3
GO
{ echo "// Code generated by sqlc. DO NOT EDIT."; echo "package p"; golines 60; } > "$PROJ/gen.go"
for i in $(seq 1 12); do echo "- line $i"; done > "$PROJ/AGENTS.md"   # > agents_md_max(10)
{ echo "package p"; for i in $(seq 1 30); do echo "// chat $i"; echo "var y$i = $i"; done; } > "$PROJ/chatty.go"  # 61 lines, ~50% comments

OUT="$(wf hygiene check --format json)"
[ "$(jget "$OUT" "d['verdict']")" = "report" ] && ok "full sweep: verdict is report" || bad "full verdict" "$OUT"
wf hygiene check >/dev/null 2>&1 && ok "full sweep exits 0 despite findings" || bad "full exit" "nonzero"

has() { jget "$1" "any(f['rule']=='$2' and f['file']=='$3' for f in d['findings'])"; }
[ "$(has "$OUT" file-length long.go)" = "True" ] && ok "H1: file over error cap flagged" || bad "H1 error" "$OUT"
[ "$(jget "$OUT" "[f['severity'] for f in d['findings'] if f['file']=='long.go' and f['rule']=='file-length'][0]")" = "error" ] \
  && ok "H1: over error cap carries severity error" || bad "H1 sev" "$OUT"
[ "$(jget "$OUT" "[f['severity'] for f in d['findings'] if f['file']=='midsize.go'][0]")" = "warn" ] \
  && ok "H1: file over warn cap carries severity warn" || bad "H1 warn" "$OUT"
[ "$(has "$OUT" func-length bigfunc.go)" = "True" ] && ok "H2: long Go function flagged" || bad "H2" "$OUT"
[ "$(has "$OUT" comment-block comments.go)" = "True" ] && ok "H3a: long comment block flagged" || bad "H3a" "$OUT"
[ "$(has "$OUT" spec-narrative comments.go)" = "True" ] && ok "H3b: spec-narrative comment block flagged" || bad "H3b" "$OUT"
[ "$(jget "$OUT" "sum(1 for f in d['findings'] if f['rule']=='spec-narrative')")" = "1" ] \
  && ok "H3b: the [REQ:] tag line alone is not narrative" || bad "H3b tag exempt" "$OUT"
[ "$(jget "$OUT" "any(f['file']=='gen.go' for f in d['findings'])")" = "False" ] && ok "generated file skipped" || bad "generated" "$OUT"
mkdir -p "$PROJ/.wf/tools"; { echo "package p"; golines 45; } > "$PROJ/.wf/tools/machinery.go"
OUT="$(wf hygiene check --format json)"
[ "$(jget "$OUT" "any(f['file'].startswith('.wf/') for f in d['findings'])")" = "False" ] && ok ".wf/ machinery excluded from sweep" || bad ".wf excluded" "$OUT"
rm -rf "$PROJ/.wf/tools"
[ "$(has "$OUT" agents-md-length AGENTS.md)" = "True" ] && ok "AGENTS.md over cap flagged" || bad "agents cap" "$OUT"
[ "$(has "$OUT" comment-ratio chatty.go)" = "True" ] && ok "H3c: comment-heavy file flagged" || bad "H3c" "$OUT"

# ---------------------------------------------------------------------------
# ratchet mode (--diff-base): errors only on what the diff made worse
# ---------------------------------------------------------------------------

rm "$PROJ"/comments.go "$PROJ"/bigfunc.go "$PROJ"/chatty.go "$PROJ"/AGENTS.md "$PROJ"/midsize.go
{ echo "package p"; golines 38; } > "$PROJ/nearcap.go"               # 39 lines, just under file_error
echo "package p" > "$PROJ/clean.go"
git -C "$PROJ" add -A; git -C "$PROJ" commit -qm base

# a diff that introduces nothing worse → no regressions
echo "var ok1 = 1" >> "$PROJ/clean.go"
OUT="$(wf hygiene check --diff-base HEAD --format json)"
[ "$(jget "$OUT" "d['verdict']")" = "pass" ] && ok "ratchet: a benign diff passes" || bad "ratchet clean" "$OUT"
git -C "$PROJ" checkout -q clean.go

# pre-existing debt (long.go) merely re-reported, not a regression
[ "$(jget "$OUT" "len(d['regressions'])")" = "0" ] && ok "ratchet: pre-existing debt is not a regression" || bad "ratchet debt" "$OUT"

# a touched file gaining a long comment block → regression, exit 1
cat >> "$PROJ/clean.go" <<'GO'

// r one
// r two
// r three
// r four
// r five
GO
OUT="$(wf hygiene check --diff-base HEAD --format json)" && bad "ratchet: new comment block should exit 1" "$OUT" \
  || ok "ratchet: introduced comment block exits 1"
[ "$(jget "$OUT" "d['regressions'][0]['rule']")" = "comment-block" ] && ok "ratchet: regression names the rule" || bad "ratchet rule" "$OUT"
git -C "$PROJ" checkout -q clean.go

# existing file growing past file_error → warn only (a split is planning work, not the build's)
{ golines 4; } >> "$PROJ/nearcap.go"                                  # 39 → 43 lines, crosses 40
OUT="$(wf hygiene check --diff-base HEAD --format json)" \
  && ok "ratchet: existing file crossing the cap stays exit 0" || bad "ratchet grow" "$OUT"
[ "$(jget "$OUT" "any(f['rule']=='file-length' and f['file']=='nearcap.go' for f in d['findings'])")" = "True" ] \
  && ok "ratchet: the crossing is still reported" || bad "ratchet grow report" "$OUT"
git -C "$PROJ" checkout -q nearcap.go

# a NEW file born over the cap → regression, exit 1
{ echo "package p"; golines 45; } > "$PROJ/newborn.go"
OUT="$(wf hygiene check --diff-base HEAD --format json)" && bad "ratchet: new file over cap should exit 1" "$OUT" \
  || ok "ratchet: new file over cap exits 1"
[ "$(jget "$OUT" "d['regressions'][0]['file']")" = "newborn.go" ] && ok "ratchet: regression names the new file" || bad "ratchet newborn" "$OUT"
rm "$PROJ/newborn.go"

# an unchanged file with debt is not even re-checked in ratchet mode
echo "var scope = 1" >> "$PROJ/clean.go"
OUT="$(wf hygiene check --diff-base HEAD --format json)"
[ "$(jget "$OUT" "any(f['file']=='long.go' for f in d.get('findings',[]))")" = "False" ] \
  && ok "ratchet: unchanged files are not swept" || bad "ratchet scope" "$OUT"
git -C "$PROJ" checkout -q clean.go

# ---------------------------------------------------------------------------
# the tree linted is the caller's, not the config's; a no-change ratchet is not a pass
# ---------------------------------------------------------------------------

# a ratchet that finds nothing changed is `empty` + exit 1, never a silent pass
OUT="$(wf hygiene check --diff-base HEAD --format json)" && bad "ratchet: no-change should exit 1" "$OUT" \
  || ok "ratchet: a no-change tree exits 1"
[ "$(jget "$OUT" "d['verdict']")" = "empty" ] && ok "ratchet: no-change verdict is 'empty'" || bad "ratchet empty verdict" "$OUT"

# invoked from a DIFFERENT tree, the diff comes from that tree — not the config's root
OTHER="$(mktemp -d)"
git -C "$OTHER" init -q; git -C "$OTHER" config user.email t@t; git -C "$OTHER" config user.name t
{ echo "package p"; golines 3; } > "$OTHER/seed.go"
git -C "$OTHER" add -A; git -C "$OTHER" commit -qm base
{ echo "package p"; golines 45; } > "$OTHER/elsewhere.go"            # over file_error → regression
OUT="$( cd "$OTHER" && "$PYTHON" "$WF" hygiene check --diff-base HEAD --format json \
        --config "$PROJ/.wf/config.yaml" )" \
  && bad "cwd-rooted: other tree's new oversized file should exit 1" "$OUT" \
  || ok "cwd-rooted: the caller's tree is the one linted"
[ "$(jget "$OUT" "d['regressions'][0]['file']")" = "elsewhere.go" ] \
  && ok "cwd-rooted: regression names the caller-tree file" || bad "cwd-rooted file" "$OUT"

echo
echo "  hygiene: $pass passed, $fail failed"
[ "$fail" -eq 0 ] || exit 1
