#!/usr/bin/env python3
"""brief.py — the AI-facing projection of the read-view (companion to render.py).

render.py emits view.html for a human; brief.py emits brief.md for an AGENT to load
at the top of a planning session. Same inputs (model.json + subsystems.json), but a
compact, token-efficient markdown digest instead of an interactive page: the system
summary, each subsystem with its components' one-line descriptions, and the
cross-cutting couplings.

This file is a SEMANTIC CACHE: the subsystem grouping + descriptions are LLM-derived,
regenerated on every discover run, never hand-edited, never committed. Treat it as
disposable orientation, not durable truth — when in doubt, re-run discover.

Usage:  brief.py --model model.json --subsystems subsystems.json --out brief.md [--title T]
"""
import argparse, json
from collections import defaultdict


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--subsystems", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--title", default="system")
    a = ap.parse_args()

    nodes = json.load(open(a.model))["nodes"]
    sub = json.load(open(a.subsystems))
    subsystems = sub["subsystems"]
    cd = sub.get("component_descriptions", {})

    sub_of = {}
    for i, s in enumerate(subsystems):
        for u in s["members"]:
            sub_of[u] = i

    def desc(u):
        return (cd.get(u) or nodes[u].get("synopsis") or "").strip() or "(no description)"

    total_loc = sum(n["loc"] for n in nodes.values())
    langs = sorted({n["lang"] for n in nodes.values()})

    L = []
    L.append(f"# {a.title} — system brief")
    L.append("> AI-facing read-view. Structure is toolchain-derived; subsystem grouping and")
    L.append("> descriptions are an LLM-derived **semantic cache** — regenerated by `discover`")
    L.append("> on demand, never hand-edited, never committed. Disposable orientation, not truth.")
    L.append("")
    L.append(sub.get("system_summary", ""))
    L.append("")
    L.append(f"**{len(nodes)} components · {len(subsystems)} subsystems · {total_loc:,} LOC · {', '.join(langs)}**")
    L.append("")

    L.append("## Subsystems")
    for s in subsystems:
        mem = [u for u in s["members"] if u in nodes]
        sloc = sum(nodes[u]["loc"] for u in mem)
        slangs = "/".join(sorted({nodes[u]["lang"] for u in mem}))
        L.append("")
        L.append(f"### {s['name']}  ·  {len(mem)} comp · {sloc:,} LOC · {slangs}")
        if s.get("summary"):
            L.append(s["summary"])
        for u in sorted(mem, key=lambda u: -nodes[u]["loc"]):
            n = nodes[u]
            health = "" if (n["has_doc"] and n["has_tests"]) else \
                     " ⚠" + ("" if n["has_doc"] else "no-doc") + (" no-tests" if not n["has_tests"] else "")
            L.append(f"- `{n['id']}` ({n['loc']} LOC{health}) — {desc(u)}")

    dis = sub.get("disagreements", [])
    if dis:
        L.append("")
        L.append("## Cross-cutting couplings")
        L.append("*Where folder / import / git-history clusterings disagree — often the highest-blast-radius edits.*")
        for d in dis:
            comps = ", ".join(f"`{nodes[u]['id']}`" for u in d.get("components", []) if u in nodes)
            L.append(f"- {d['finding']}" + (f"  ({comps})" if comps else ""))

    open(a.out, "w").write("\n".join(L) + "\n")
    print(f"wrote {a.out}  ({len(nodes)} components, {len(subsystems)} subsystems)")


if __name__ == "__main__":
    main()
